foods/urls.py
from django.urls import path
from . import views

app_name = "foods"
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:item_id>/', views.detail, name='detail'),
    path('item/', views.item, name="item"),
    path('add', views.create_food, name="create_food"),
    path('update/<int:id>', views.update_food, name="update_food"),
    path('delete/<int:id>', views.delete_food, name="delete_food")
]

my_menu/urls.py
from django.contrib import admin    
from django.urls import include,path
from django.contrib.auth import views as authentication_views
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('foods/', include('foods.urls')),
    path('register/',user_views.register,name='register'),
]

foods/models.py
from django.db import models

class Item(models.Model):
    item_name = models.CharField(max_length=200)
    item_subtitle = models.CharField(max_length=20)
    item_desc = models.CharField(max_length=900)
    item_image = models.CharField(max_length=500, default="https://anvilhotel.com/wp-content/uploads/2017/08/food-placeholder.png")

    def __str__(self):
        return self.item_name
    
    

users/models.py
from django.db import models

# Create your models here.

foods/forms.py
from django import forms 
from .models import Item

class FoodForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["item_name", "item_subtitle", "item_desc", "item_image"]

foods/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from .forms import FoodForm

def index(request):
    item_list = Item.objects.all()
    
    context = {
        'item_list': item_list,
    }
    
    return render(request, 'index.html', context)


def item(request):
    return render(request, 'item.html')


def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item': item,
    }
    return render(request, 'detail.html', context)


def create_food(request):
    form = FoodForm(request.POST or None)
    
    if form.is_valid():
        form.save()
        return redirect('foods:index')
    
    return render(request, 'food-form.html', {'form': form })

def update_food(request, id):
    item = Item.objects.get(id=id)
    form = FoodForm(request.POST or None, instance=item)
    
    if form.is_valid():
        form.save()
        return redirect('foods:index')
    
    return render(request, 'food-form.html', {'form': form, 'item': item })

def delete_food(request, id):
    item = Item.objects.get(id=id)
    
    if request.method == 'POST':
        item.delete()
        return redirect('foods:index')
    
    return render(request, 'food-delete.html', {'item': item })    

users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'welcome {username}, your account is created')
            return redirect('foods:index')
        else:
            form = UserCreationForm()
        return render(request, 'user/register.html', { 'form': form })

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>My Menu {% block title %} {% endblock %}</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="My Recipe Menu">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.14.0/css/mdb.min.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
</head>
  <body>

    <div>
    
        {% include 'partials/_navbar.html' %}
        {% if messagess %}
          {% for message in messages %}
            {{ message }}
          {% endfor %}
        {% endif %}
        {% block content %} {% endblock %}
      
    </div>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.14.0/js/mdb.min.js"></script>

  </body>
</html>

templates/detail.html
{% extends 'base.html' %}
{% load static %}


{% block title %} | Welcome {% endblock %}

{% block content %}

<h1>Dteails Page</h1>

<br/>
<br/>

<div class="conatiner">
    <div class="row">
        <div class="col-md-6">
            <img height="300px" src="{{ item.item_image }}" class="card" />
        </div>
        <div class="col-md-6">
            <h1>{{item.item_name}}</h1>
             <p>{{item.item_subtitle}}</p>
        
            <p>{{item.item_desc }}</p>
            <a href="{% url 'foods:delete_food' item.id %}">Delete</a>
        </div>   
    </div>
</div>



{% endblock %}

templates/food-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{item.item_name}}</h2>
    <button type="submit">Confirm</button>
</form>

templates/food-form.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {% endblock %}


{% block content %}

    <div class="container">
        <div class="container mt-5 pt-5">
            <form method="POST">
                {% csrf_token %}
                {{ form }}
                <button type="submit">Save</button>
            </form>
        </div>
    </div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block title %} | Welcome {% endblock %}

{% block content %}

<br/>
<div class="container">
{% for food in item_list %}
    <div class="row">
        <div class="col-md-3 offset-md-2">
            <img class="card" height="150px" src="{{food.item_image}}"/>
        </div>
        <div class="col-md-4">
            <h3>{{food.item_name}}</h3>
            <h5>{{food.item_desc}}</h5>
            <h6>$ {{food.item_price}}</h6>
        </div>
        <div class="col-md-2">
            <a href="{% url 'foods:detail' food.id %}" class="btn btn-info">Details</a>
        </div>
    </div>
{% endfor %}
<br/>
</div>


   {% comment %} <a href="{% url 'foods:detail' food.id %}"> {{ food.item_name}} </a>
    <p>{{ food.item_desc}}</p>
   <p> {{ food.item_price}}</p> {% endcomment %}
    



{% endblock %}

templates/item.html
<h1>Item</h1>

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark info-color">
  <a class="navbar-brand" href="{% url 'foods:index' %}">My Menu</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
    aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="basicExampleNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'foods:create_food' %}">Add</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Delete</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">View Menu</a>
      </li>
    </ul>
  </div>
</nav>

templates/user/register.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit"> Signup</button>
</form>